[package]
name = "tomaslang"
version = "0.1.0"
edition = "2021"

[dependencies]
signal-hook = "0.3.17"
termios = "0.3.3"

[profile.release]
debug = true

[features]
debug_trace_execution = []
debug_disassemble = []
debug_raw = []
